l = input('digite algo')
print('e um numero ?', type(l))
print('so tem espaço',l.isspace())
print('e um numero ?',l.isalnum())
print('e alfabetico ?',l.isalpha())
print('e alfa nemerico',l.isalnum())
print('esta em maiusculas ?',l.isupper())
print('esta em minusculo ?',l.islower())
print('esta capitalizada ?',l.istitle())